modLoader="javafml"
loaderVersion="[38,)"
license="MIT License"
[[mods]]
modId="bk"
version="${file.jarVersion}"
displayName="Beekeeper"
displayURL="https://www.curseforge.com/minecraft/mc-mods/beekeeper"
logoFile="logo.png"
authors="Lupicus, MacTso"
description='''Beekeeper'''
[[dependencies.bk]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bk]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
